markdown: kramdown
permalink: pretty

future: true

image_root: /assets/img/o/
coming_soon_card_text: Coming soon...

sass:
  sass_dir: assets/css
  style: :nested

collections:
  play:
    output: true
    permalink: /:collection/:name/
  playFuture:
    output: true
    permalink: /play/:name/
  audioShows:


defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      permalink: "/:basename/"
  -
    scope:
      path: "" # empty string for all files in the project
      type: "playFuture"
    values:
      location: "Location TBA"
      poster_thumb: "https://cdn.ticketsource.co.uk/images/search/default1.png"
  -
    scope:
      path: "" # empty string for all files in the project
    values:
      image: /assets/img/edclogo.png

exclude:
  - readme.md
  - cibuild.sh
  - vendor

plugins:
  - jekyll-seo-tag

description: Exeter Drama Company is a small amateur theatre group who put on plays four times a year. If you are interested in seeing a play or becoming a member....
url: "https://www.exeterdramacompany.co.uk"
title: Exeter Drama Company
lang: en_GB

social_links:
  twitter: https://www.twitter.com/ExeterDramaCo
  facebook: https://www.facebook.com/ExeterDramaCompany
  ticketsource: https://www.ticketsource.co.uk/ExeterDrama
  email: exeterdramaco.publicity@gmail.com
  fundraising: https://www.easyfundraising.org.uk/causes/exeterdramacompany
  campaign: https://cafdonate.cafonline.org/13478
  instagram: https://www.instagram.com/exeterdramacompany

facebook:
    app_id: https://www.facebook.com/ExeterDramaCompany
